### ISSUE TITLE
pod update  couldn't  download the sdk

### ISSUE THREAD

**Issue by Li-Qun** [yenom/BitcoinKit#178] opened 2018-11-05 05:43 UTC
# Current behavior

# Expected behavior

# Steps to reproduce
1.  pod update
2. terminal  call wrong:
[!] /bin/bash -c
set -e
sh setup/build_libraries.sh

++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh
+ trap '{ cd - ; rm -rf /var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh; exit 255; }' SIGINT
+ cd /var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh
+ TARGETDIR_IPHONEOS=/var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh/.build/iphoneos
+ mkdir -p /var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh/.build/iphonesimulator
+ mkdir -p /var/folders/wb/94fnm3z10kx173vpc3nj1y340000gn/T/tmp.FOGQuhGh/.build/iphonesimulator
+ cd src
+ ./autogen.sh
./autogen.sh: line 3: autoreconf: command not found
3.  

# Environment

- BitcoinKit: *lastest*
- Xcode Version: *10.0*
- Swift Version: *4.2*

**Comment by akifuji** [comment] 2018-11-05 06:03
@Li-Qun Duplicate of #42 . Please install autoconf automake.

**Comment by akifuji** [comment] 2018-11-06 02:46
@Li-Qun 
Looks like the duplicate of #52. Please check it out!

**Closed** 2018-11-09 02:50 UTC
